### PR TITLE
update version for prometheus to 4.5 (#1912)

### PR DESCRIPTION
**Pull request by cclhsu**
update version for prometheus to 4.5 (#1912)

refs: https://github.com/SUSE/avant-garde/issues/1912

Signed-off-by: cclhsu <clark.hsu@suse.com>

### CODE REVIEW

**Comment by dirkmueller** [comment]
@kkaempf  fyi the plan of action was that the ecosystem team will take over maintaining this, so near/mid term the chart will be moved over to a non-caasp space. what should be done to make that happen?

**Comment by kkaempf** [comment]
:thinking: `kubernetes-charts-suse-com` should be generic and not caasp-specific. What makes you think you need a non-caasp space ?

**Comment by dirkmueller** [comment]
ok, right, I was talking about the images, not the chart: https://github.com/SUSE/kubernetes-charts-suse-com/pull/187/files#diff-fbfed325fbf0837623bc57eb7578702dR545-R546 however those go hand in hand.

**Comment by cclhsu** [comment]
@maximenoel8 Can you help test this if ok to merge?

**Review by maximenoel8 — APPROVED** [review]
LGTM

**Comment by c3y1huang** [comment]
Image tag and appVersion needs to be updated also.

**Comment by c3y1huang** [comment]
Need a rebase.

**Review by c3y1huang — APPROVED** [review]

**Review by innobead — APPROVED** [review]

**Review by jordimassaguerpla — APPROVED** [review]

**Pull request merged**
