### PR TITLE
Bump velero container image to v4.5

### PR DESCRIPTION
**Pull request by jenting**
xrefs https://github.com/SUSE/avant-garde/issues/1912

### CODE REVIEW

**Comment by jenting** [comment]
the CI use helm version `v3.3.0` and I encountered this issue https://github.com/helm/charts/issues/23547

**Comment by jenting** [comment]
@maximenoel8 @cclhsu @innobead @c3y1huang PTAL :bow:

**Comment by c3y1huang** [comment]
CI not happy.

**Comment by jenting** [comment]
> CI not happy.

Yes, it's because the CI use the latest helm version 3.3.0 and from helm 3.3.0, it changes the linter behavior that must match Kubernetes qualified name which I think it's a bug and it does not affect current helm chart.

Anyway, I'll keep watch the helm upstream feedback.

**Comment by c3y1huang** [comment]
> > CI not happy.
> 
> Yes, it's because the CI use the latest helm version 3.3.0 and from helm 3.3.0, it changes the linter behavior that must match Kubernetes qualified name which I think it's a bug and it does not affect current helm chart.
> 
> Anyway, I'll keep watch the helm upstream feedback.

Considering moving `{{- if and .Values.installCRDs .Values.cleanUpCRDs  }}` up to the first line. This packs the comments inside and should resolve the issue.
```
{{- if and .Values.installCRDs .Values.cleanUpCRDs  }}
# This job is meant primarily for cleaning up on CI systems.
# Using this on production systems, especially those that have multiple releases of Velero, will be destructive.
apiVersion: batch/v1
```

**Comment by c3y1huang** [comment]
Created [[velero] Fix helm 3.3.0 lint issue](https://github.com/vmware-tanzu/helm-charts/pull/150).

**Comment by jenting** [comment]
> Created [[velero] Fix helm 3.3.0 lint issue](https://github.com/vmware-tanzu/helm-charts/pull/150).

cool~, many thanks

**Review by c3y1huang — APPROVED** [review]

**Comment by c3y1huang** [comment]
Need to bump up chart version too.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
cc @cclhsu

**Comment by maximenoel8** [comment]
LGTM.

Tested with GC, azure and AWS

**Review by maximenoel8 — APPROVED** [review]

**Review by cclhsu — APPROVED** [review]

**Pull request merged**
