### PR TITLE
Bump velero version (app=1.4.2,chart=2.13.0)

### PR DESCRIPTION
**Pull request by jenting**
- chart version to 2.13.0
- app version to 1.4.2

xref https://github.com/SUSE/avant-garde/issues/1786

Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by jenting** [comment]
test with devel image

- helm3
```
helm install velero \
  --namespace=velero \
  --create-namespace \
  --set-file credentials.secretContents.cloud=credentials-velero \
  --set configuration.provider=aws \
  --set configuration.backupStorageLocation.name=default \
  --set configuration.backupStorageLocation.bucket=velero \
  --set configuration.backupStorageLocation.config.region=minio-default \
  --set configuration.backupStorageLocation.config.s3ForcePathStyle=true \
  --set configuration.backupStorageLocation.config.s3Url=http://minio-default.velero.svc.cluster.local:9000 \
  --set configuration.backupStorageLocation.config.publicUrl=http://localhost:9000 \
  --set snapshotsEnabled=true \
  --set deployRestic=true \
  --set configuration.volumeSnapshotLocation.name=default \
  --set configuration.volumeSnapshotLocation.config.region=minio-default \
  --set initContainers[0].name=velero-plugin-for-aws \
  --set initContainers[0].image=registry.suse.de/devel/caasp/4.5/containers/containers/caasp/v4.5/velero-plugin-for-aws:1.1.0 \
  --set initContainers[0].volumeMounts[0].mountPath=/target \
  --set initContainers[0].volumeMounts[0].name=plugins \
  --set image.repository=registry.suse.de/devel/caasp/4.5/containers/containers/caasp/v4.5/velero \
  --set configMaps.restic-restore-action-config.data.image=registry.suse.de/devel/caasp/4.5/containers/containers/caasp/v4.5/velero-restic-restore-helper:1.4.2 \
  velero
```

- helm2
```
helm install --name=velero \
  --namespace=velero \
  --set-file credentials.secretContents.cloud=credentials-velero \
  --set configuration.provider=aws \
  --set configuration.backupStorageLocation.name=default \
  --set configuration.backupStorageLocation.bucket=velero \
  --set configuration.backupStorageLocation.config.region=minio-default \
  --set configuration.backupStorageLocation.config.s3ForcePathStyle=true \
  --set configuration.backupStorageLocation.config.s3Url=http://minio-default.velero.svc.cluster.local:9000 \
  --set configuration.backupStorageLocation.config.publicUrl=http://localhost:9000 \
  --set snapshotsEnabled=true \
  --set deployRestic=true \
  --set configuration.volumeSnapshotLocation.name=default \
  --set configuration.volumeSnapshotLocation.config.region=minio-default \
  --set initContainers[0].name=velero-plugin-for-aws \
  --set initContainers[0].image=registry.suse.de/devel/caasp/4.5/containers/containers/caasp/v4.5/velero-plugin-for-aws:1.1.0 \
  --set initContainers[0].volumeMounts[0].mountPath=/target \
  --set initContainers[0].volumeMounts[0].name=plugins \
  --set image.repository=registry.suse.de/devel/caasp/4.5/containers/containers/caasp/v4.5/velero \
  --set configMaps.restic-restore-action-config.data.image=registry.suse.de/devel/caasp/4.5/containers/containers/caasp/v4.5/velero-restic-restore-helper:1.4.2 \
  velero
```

**Comment by cclhsu** [comment]
@maximenoel8 Can you help test this if ok to merge?

**Comment by innobead** [comment]
Waiting for the upstream to merge as well. https://github.com/vmware-tanzu/helm-charts/pull/146

**Comment by jenting** [comment]
@cclhsu 
QA has done the verification https://github.com/SUSE/avant-garde/issues/1786#issuecomment-708123211
This is ready to be released.

**Comment by jenting** [comment]
@cclhsu Will this be released recently?

**Comment by cclhsu** [comment]
@jenting yes, 4.5.2 is in progress of releasing this week. once it is done we can also merge this.

**Pull request closed without merging**
