### PR TITLE
Bump rsyslog container image in log-agent-rsyslog to v4.5

### PR DESCRIPTION
**Pull request by c3y1huang**
Updates log-agent-rsyslog to v4.5 repo. 

Verified deployment and log forwarding with the default setting.

Ref: https://github.com/SUSE/avant-garde/issues/1912

### CODE REVIEW

**Comment by c3y1huang** [comment]
cc/ @cclhsu @jenting @maximenoel8 @innobead

**Review by jenting — APPROVED** [review]

**Review by innobead — APPROVED** [review]

**Comment by c3y1huang** [comment]
rebased.

**Comment by c3y1huang** [comment]
rebased

**Review by cclhsu — APPROVED** [review]

**Comment by cclhsu** [comment]
@maximenoel8 Can you help test this if ok to merge?

**Comment by c3y1huang** [comment]
rebased

**Review by maximenoel8 — APPROVED** [review]
LGTM

**Comment by c3y1huang** [comment]
@cclhsu I think this is ready to merge.

**Pull request merged**
