### PR TITLE
update version for grafana to 4.5 (#1912)

### PR DESCRIPTION
**Pull request by cclhsu**
update version for grafana to 4.5 (#1912)

refs: https://github.com/SUSE/avant-garde/issues/1912

Signed-off-by: cclhsu <clark.hsu@suse.com>

### CODE REVIEW

**Comment by cclhsu** [comment]
@maximenoel8 Can you help test this if ok to merge?

**Review by maximenoel8 — APPROVED** [review]
LGTM

**Comment by c3y1huang** [comment]
Image tag and appVersion needs to be updated also.

**Comment by c3y1huang** [comment]
Need to rebase.

**Review by c3y1huang — APPROVED** [review]

**Review by innobead — APPROVED** [review]

**Review by jordimassaguerpla — APPROVED** [review]

**Pull request merged**
